### ISSUE TITLE
Update Mozilla logo in DUO from old to new

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/mozilla-iam#38]
The current DUO instance utilizes the old Mozilla logo and needs updating to the current [black and white Mozilla logo](https://mozilla.ninja/s/Mozilla-logo-BW-RGB.zip).﻿﻿ 
<img width="287" alt="duo-update-logo" src="https://user-images.githubusercontent.com/18686986/36042988-a71de22a-0d82-11e8-993a-4dfe37db167f.png">
If this could possibly be done by FEB 14 it would improve the NLX user testing experience. :)

**Comment by gdestuynder** [comment]
![image](https://user-images.githubusercontent.com/956866/36044529-d39c7924-0d87-11e8-866f-9e39caa4bbd4.png)
All done

**Comment by m-branson** [comment]
@gdestuynder possible to size the logo to be smaller than, or match the height of, the 'settings' button? 😬 Thanks!

**Comment by gdestuynder** [comment]
it seems hard to do because we do not control the page. the css enforces a max-height of 48px and auto-width which means, if i make the logo smaller than 48px it elongates it and it looks pretty bad
i tried by filling with transparent space though im probably not the best at this.

note, using the duo recommendations (302x302) it looks like that:

![image](https://user-images.githubusercontent.com/956866/36114596-49cd7b5c-0fe5-11e8-96dc-a89d90459d7c.png)

**Comment by gdestuynder** [comment]
This is as good as i could do:

![image](https://user-images.githubusercontent.com/956866/36115153-1ad89a6e-0fe7-11e8-911b-e19f19896efd.png)
i used transparency to offset everything. im hoping this looks sufficiently aligned in all browsers

**Comment by m-branson** [comment]
Thanks @gdestuynder appreciate you walking through the barriers, looks good!
