### ISSUE TITLE
"Autologging in with email" error

### ISSUE THREAD

**Issue by madb1lly** [mozilla-iam/mozilla-iam#43]
Hi,

I use passwordless logon to Mozilla sites using my gmail address. I'm currently logged into Discourse, but when I tried to log into Mozillians.org I got this error:
Cannot GET /wsfed?disable_signup=false&name=email&email=&authParams=&totp=&brute_force_protection=true&store=&strategy_instance=email&wctx=TkUpjzrX7-PSVcDWfoesa_Rrt-Ft_iZ_&wtrealm=urn%3Aauth0%3Aauth%3Aemail&wa=wsignin1.0 

I've managed to log into Mozillians before, but now I can't. I used container tabs and was able to log into Mozillians, but in my normal session it's not possible.

Is this a bug or a problem with my Firefox set up?

Cheers :)

**Comment by hidde** [comment]
Hello @madb1lly , thanks for reporting this! 

This is indeed a due to a bug that existed in an earlier version of our login form. Because of the bug, the login form remembers Passwordless login as your autologin method. 

The solution is to clear the data that has this information in it. You can do this by going to `about:preferences#privacy` and use ‘Clear all data’ under ‘Site data’.

Alternatively, you can clear only the login form's data. To do this, enter `localStorage.clear()` into the Console in Developer Tools, while the login page is open.

Hope this helps!

**Comment by madb1lly** [comment]
Thanks. I think I'll have to clear data for all sites because when I open the login page it automatically tries to log me in and then goes to error - the whole process lasts only a few seconds, not long enough to try and use the console.

Probably a good idea to clear my cache anyway, good habit to get into :D

**Comment by gdestuynder** [comment]
considering this is solved - feel free to reopen if I'm mistaken

**Comment by madb1lly** [comment]
I just tried to login to discourse.mozilla.org in Firefox 59.0.2 and got the same problem, so it looks like some Mozilla websites haven't been upgraded. Unless I've misunderstood and this is a Firefox bug, but Firefox has been upgraded since I first had the problem.

**Comment by gdestuynder** [comment]
@hidde

**Comment by madb1lly** [comment]
Hi @hidde ,
The steps you've followed are correct. I have not had the problem in the past few weeks, so I assume that it has been fixed. I'm current on Firefox 60.0.01 on Windows 7, but I don't think I've tried on the beta or other platforms. If I have the problem again I will tell you.
Thanks,
