### ISSUE TITLE
If we don't have mobile phone (or don't want give its number) we can't authanticate with GitHub ?

### ISSUE THREAD

**Issue by decembre** [mozilla-iam/mozilla-iam#45]
I read:
- https://discourse.mozilla.org/t/important-changing-the-look-of-your-login/25843/16
- https://wiki.mozilla.org/IAM/Frequently_asked_questions#New_Login_Experience_FAQ_.28Frequently_Asked_Questions.29

I don't appreciate the use of our mobile number for security reason (or telephone number too).
Maybe i am too old school but ...

Your new login form is to complicate to me ... sorry.

And it don't give sufficient alternative way to authenticate or i don't understand them.

Can you be more friendly , please ?

**Comment by hmitsch** [comment]
Hi @decembre,

thanks for reaching out! You can use any TOTP-compliant application for GitHub 2FA. There is no need to use SMS authentication.

Can you tell us more about the things that make the login form seem complicated?

Hope this response is a first step to help you see that we try to be friendly.
Best regards,
   Henrik

**Comment by decembre** [comment]
Thanks Henrik, i know you want to be user friendly.
BUT seriously :
  "TOTP-compliant application for GitHub 2FA"..... 
.... haaarrrg :-)

I do a search:
https://duckduckgo.com/?q=+TOTP-compliant+application&ia=web

Find some little infos like:
_How to obviate loosing access when using two-factor-authentication_
(https://superuser.com/questions/1234276/how-to-obviate-loosing-access-when-using-two-factor-authentication):
_"You can use a TOTP-compliant app that will share your logins across multiple devices, such as Authy or 1Password and store them in the cloud. Of course, that's also a bit less secure, since it gives you another way that your logins can leak. I personally use Authy to share my two-factor logins across four different devices."_

pfffou.... i do my best (yes, that's maybe i have not the level required here or/and my English is not sufficient) but it seems too waste time for me to understand these jargon for only share an idea or comment.

Yes , it seems more easy to give this dam phone number....

My bank, ok. They know "all" of me , they have the infos.
Ok : send the SMS !!.
But for just comments or ask something on https://discourse.mozilla.org/  ???

I am not interesting by the "two factor authorization" but they "force" us/me to use it.
When  i try their new login form, it return a very "obfuscate" error message.
After it want only Github as login auth.

I am too old.

**Comment by andrewkrug** [comment]
@decembre I'm really sorry to hear that you're having trouble finding the right solution for 2nd Factor Authentication.  Navigating this space can be generally confusing as everyone uses different acronyms and 2 Factor protocols.  

I personally use Mozilla Identity and Access Management with a hardware key called a yubikey.  I've linked it below.  The latest version of firefox supported U2F _( also known as universal 2nd factor )_ and so does github.  ( https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/ ). When using a hardware key like a U2F token you only need to tap the device when prompted for a second factor.

**YubiKey 4 and 4c**
https://www.yubico.com/products/yubikey-hardware/yubikey4/?gclid=EAIaIQobChMIxPuH-8T42QIVjYp-Ch0SCwecEAAYAiAAEgLCUPD_BwE

Regarding the error page confusion.  **_My apologies there._**  We had a legitimate bug due to an issue in python cryptography that was patched last Friday preventing our error page from returning you a more meaningful message.

So ... in summary here is my reccomended steps to get you using 2 Factor authentication without barriers or SMS messages.  

1. Get a hardware token ( yubikey or other ) that supports U2F.  I've linked it above.  If the yubikey 4 seems a bit pricey you can go with this model instead that ONLY does U2F to save a few euros.  https://www.amazon.com/FIDO-U2F-Security-Key-co-creator/dp/B00NLKA0D8
2. Enroll that as a U2F device with github. https://help.github.com/articles/configuring-two-factor-authentication-via-fido-u2f/
3. Follow up here and let us know how you found the experience. 

Thanks again for all of your engagement and feedback.

Andrew J Krug
Security Engineer
Identity and Access Management

**Comment by gdestuynder** [comment]
Note that you can also use free OTP applications on your phone (this does not use your phone number) as well, as per FAQ, if you prefer that option.

Considering this solved since SMS/phone number is not required.

**Comment by decembre** [comment]
Thanks folks for the help.
Yes , now the login page i usable ;-)

But i asked a 2 factors "without " any mobile .....
I don't want use/buy any "security hardware token"  too.

Old school man try to keep things simple (i hope).
I don't imagine my poor Father with its Parkinson ability fighting with this beautiful 2 Factors key if  it become the standard.
